---

- name: Install package
  apt: name=nginx state=present

- name: Configure service
  template: src=nginx.conf.j2 dest=/etc/nginx.conf
  notify: restart nginx

- name: Create configuration directory
  file: dest=/etc/nginx/conf.d state=directory

- name: Create site directory
  file: dest=/etc/nginx/sites-enabled state=directory

- name: Configure service
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf validate='/usr/sbin/nginx -t -c %s'
  notify: restart nginx

- name: Configure HTTPS
  template: src=https.conf.j2 dest=/etc/nginx/conf.d/https.conf
  notify: restart nginx

- name: Configure PHP
  template: src=php.conf.j2 dest=/etc/nginx/conf.d/php.conf
  notify: restart nginx

- name: Create Diffie-Hellmann parameters
  command: /usr/bin/openssl dhparam -out /etc/ssl/dhparams.pem 4096 creates=/etc/ssl/dhparams.pem

- name: Enable service
  service: name=nginx enabled=yes
