---

- name: reload daemons
  command: /bin/systemctl daemon-reload

- name: restart mysql
  service: name=mysql state=restarted

- name: restart nginx
  service: name=nginx state=restarted

- name: restart php-fpm
  service: name=php5-fpm state=restarted

- name: restart rrdcached
  service: name=rrdcached state=restarted

- name: restart mysqlcheck
  service: name=mysqlcheck.timer state=restarted

- name: update observium
  command: ./discovery.php -u chdir=/opt/observium
